name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore and build the solution
        working-directory: ./api
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run tests
        working-directory: ./api
        run: |
          dotnet test --no-build --configuration Release

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest ./ui
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest ./api

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest
